let a = 5; 
let x = "10"; 
const pi = 3.14;  
let gioitinh = true;  
let name = "Nam";  
let c = 'Nguyen thi B';  
let d = `VU VAN C ${a}`;  
// console.log(name);
// console.log(c);  
// console.log(d);  
let fullname = "pham van A " + name; 
 console.log(fullname);  
let nhietdo = 30; 
// console.log("nhiet do hom nay la : " + nhietdo); 
 // let m = 20; 
 // let n = "20 "; 
// console.log(m+n);
 // console.log(m); 
 // let h = Number(n) + "" + m ;    
let name = prompt("hay nhap ten cua ban");
let age = prompt("hay nhap tuoi cua ban ");  
let result = "xin chao" + name + " , ban da " + age + "tuoi";
let resultl = ` xin chao ${name}  , ban da ${age} tuoi ` ; 